# frozen_string_literal: true

source "https://rubygems.org"

gemspec

gem "rake", "~> 13.0"
gem "rake-compiler", "~> 1.2"
# Rustクレート側の`rb-sys`とバージョンを揃える。
gem "rb_sys", "~> 0.9.128"
gem "rspec", "~> 3.13"
